import React, { useState } from 'react';
import { jsPDF } from 'jspdf';
import { X, Download, Award, Loader2 } from 'lucide-react';

const CertificateModal = ({ isOpen, onClose, userName, eventTitle, eventDate, ticketId }) => {
  const [generating, setGenerating] = useState(false);

  if (!isOpen) return null;

  const generatePDF = () => {
    setGenerating(true);
    const doc = new jsPDF({
      orientation: 'landscape',
      unit: 'px',
      format: [600, 400]
    });

    // 🎨 Design: Background & Border
    doc.setFillColor(255, 255, 255);
    doc.rect(0, 0, 600, 400, 'F');
    
    doc.setLineWidth(10);
    doc.setDrawColor(79, 70, 229); // Indigo-600
    doc.rect(0, 0, 600, 400);

    // 🏆 Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(40);
    doc.setTextColor(79, 70, 229);
    doc.text("CERTIFICATE", 300, 80, { align: "center" });
    
    doc.setFontSize(16);
    doc.setTextColor(100, 100, 100);
    doc.text("OF PARTICIPATION", 300, 105, { align: "center" });

    // 👤 User Name
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text("PROUDLY PRESENTED TO", 300, 160, { align: "center" });

    doc.setFont("times", "bolditalic");
    doc.setFontSize(32);
    doc.setTextColor(30, 30, 30);
    doc.text(userName || "Student Name", 300, 200, { align: "center" });
    doc.setLineWidth(1);
    doc.line(150, 210, 450, 210); // Underline

    // 📅 Event Details
    doc.setFont("helvetica", "normal");
    doc.setFontSize(14);
    doc.text(`For successfully attending`, 300, 240, { align: "center" });
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text(eventTitle || "Event Name", 300, 265, { align: "center" });

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    doc.text(`Date: ${eventDate}`, 300, 290, { align: "center" });

    // 🆔 Footer ID
    doc.setFontSize(10);
    doc.setTextColor(200, 200, 200);
    doc.text(`Certificate ID: ${ticketId}`, 20, 380);
    doc.text("Generated by UniFlow", 500, 380);

    // Save
    doc.save(`${eventTitle.replace(/\s+/g, '_')}_Certificate.pdf`);
    setGenerating(false);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in">
      <div className="bg-white dark:bg-zinc-900 w-full max-w-md rounded-2xl p-6 text-center shadow-2xl border border-zinc-200 dark:border-zinc-800">
        <Award className="w-16 h-16 text-yellow-500 mx-auto mb-4" />
        <h2 className="text-2xl font-black text-zinc-900 dark:text-white mb-2">Claim Certificate</h2>
        <p className="text-zinc-500 mb-6">
          You have successfully attended <b>{eventTitle}</b>. Download your official certificate now.
        </p>

        <div className="flex gap-3">
          <button onClick={onClose} className="flex-1 py-3 font-bold text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-800 rounded-xl transition-colors">
            Close
          </button>
          <button 
            onClick={generatePDF} 
            disabled={generating}
            className="flex-1 py-3 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl font-bold flex items-center justify-center gap-2 shadow-lg shadow-indigo-600/20"
          >
            {generating ? <Loader2 className="w-5 h-5 animate-spin" /> : <><Download className="w-5 h-5" /> Download PDF</>}
          </button>
        </div>
      </div>
    </div>
  );
};

export default CertificateModal;